version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /examples/audit/audit_multiconfig
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /examples/audit/log
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /examples/audit/log_bulk
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /examples/audit/log_bulk_async
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /examples/audit/log_bulk_async_with_vault
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /examples/audit/log_n_sign
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /examples/audit/log_verbose
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /examples/audit/root
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /examples/audit/search
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /examples/authn/invite_actions
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /examples/authn/user_actions
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /examples/embargo/ip_check
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /examples/embargo/iso_check
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /examples/file_scan/file_scan_async_crowdstrike
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /examples/file_scan/file_scan_async_reversinglabs
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /examples/file_scan/file_scan_request_upload_url_post
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /examples/file_scan/file_scan_request_upload_url_put
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /examples/file_scan/file_scan_sync_crowdstrike
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /examples/file_scan/file_scan_sync_reversinglabs
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /examples/intel/defang/defang
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /examples/intel/domain/reputation
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /examples/intel/domain/reputation_bulk
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /examples/intel/domain/whois
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /examples/intel/file/reputation
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /examples/intel/file/reputation_bulk
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /examples/intel/file/reputation_filepath
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /examples/intel/ip/geolocate
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /examples/intel/ip/geolocate_bulk
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /examples/intel/ip/get_domain
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /examples/intel/ip/get_domain_bulk
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /examples/intel/ip/is_proxy
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /examples/intel/ip/is_proxy_bulk
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /examples/intel/ip/is_vpn
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /examples/intel/ip/is_vpn_bulk
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /examples/intel/ip/reputation_bulk
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /examples/intel/ip/reputation_crowdstrike
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /examples/intel/ip/reputation_cymru
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /examples/intel/url/reputation
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /examples/intel/user/password_breached
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /examples/intel/user/user_breached_by_email
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /examples/intel/user/user_breached_by_ip
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /examples/intel/user/user_breached_by_phone
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /examples/intel/user/user_breached_by_username
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /examples/redact/redact_multiconfig
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /examples/redact/structured
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /examples/redact/text
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /examples/vault/encrypt
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /examples/vault/encrypt_structured
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /examples/vault/get
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /examples/vault/rotate
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /examples/vault/sign
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /packages/jsondoclet
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /packages/pangea-sdk
    schedule:
      interval: daily
