default:
  image: maven:3.9.13-eclipse-temurin-21@sha256:850d3575de1cf32ee99e6da31acd943242113ee9b7d320564784a30b2f9b0a42
  tags:
    - pangea-internal

stages:
  - build
  - integration_tests
  - publish
  - examples

include:
  - /examples/.gitlab-ci.yml
  - /packages/pangea-sdk/.gitlab-ci.yml
