default:
  image: maven:3.9.11-eclipse-temurin-21@sha256:ca90b9ac00e416b1f0904bd7e68db6e37ff0d80842f65d71a77e3097659e853c
  tags:
    - pangea-internal

stages:
  - build
  - integration_tests
  - publish
  - examples

include:
  - /examples/.gitlab-ci.yml
  - /packages/pangea-sdk/.gitlab-ci.yml
