variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode --errors"

.sdk-base:
  before_script:
    - export PANGEA_INTEGRATION_TOKEN_LVE="$(eval echo \$PANGEA_INTEGRATION_TOKEN_LVE_AWS)"
    - export PANGEA_INTEGRATION_DOMAIN_LVE="$(eval echo \$PANGEA_INTEGRATION_DOMAIN_LVE_AWS)"
    - cd packages/pangea-sdk
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

sdk-integration-tests:
  stage: integration_tests
  retry: 2
  variables:
    CLOUD: AWS

    # Set each service test environment
    SERVICE_AI_GUARD_ENV: LVE
    SERVICE_AUDIT_ENV: LVE
    SERVICE_AUTHN_ENV: LVE
    SERVICE_AUTHZ_ENV: LVE
    SERVICE_EMBARGO_ENV: LVE
    SERVICE_FILE_SCAN_ENV: LVE
    SERVICE_IP_INTEL_ENV: LVE
    SERVICE_DOMAIN_INTEL_ENV: LVE
    SERVICE_URL_INTEL_ENV: LVE
    SERVICE_FILE_INTEL_ENV: LVE
    SERVICE_USER_INTEL_ENV: LVE
    SERVICE_PROMPT_GUARD_ENV: LVE
    SERVICE_REDACT_ENV: LVE
    SERVICE_SANITIZE_ENV: LVE
    SERVICE_VAULT_ENV: LVE
    SERVICE_SHARE_ENV: LVE

  before_script:
    - echo $ENV
    - echo $CLOUD
    - echo $TEST
    # Update environment variables
    # Domain
    - export PANGEA_INTEGRATION_URL_TEMPLATE_${ENV}="$(eval echo \$PANGEA_INTEGRATION_URL_TEMPLATE_${ENV}_${CLOUD})"
    # Tokens
    - export PANGEA_INTEGRATION_TOKEN_${ENV}="$(eval echo \$PANGEA_INTEGRATION_TOKEN_${ENV}_${CLOUD})"
    - export PANGEA_INTEGRATION_VAULT_TOKEN_${ENV}="$(eval echo \$PANGEA_INTEGRATION_VAULT_TOKEN_${ENV}_${CLOUD})"
    - export PANGEA_INTEGRATION_CUSTOM_SCHEMA_TOKEN_${ENV}="$(eval echo \$PANGEA_INTEGRATION_CUSTOM_SCHEMA_TOKEN_${ENV}_${CLOUD})"
    - export PANGEA_INTEGRATION_MULTI_CONFIG_TOKEN_${ENV}="$(eval echo \$PANGEA_INTEGRATION_MULTI_CONFIG_TOKEN_${ENV}_${CLOUD})"
    # Config IDs
    - export PANGEA_AUDIT_CONFIG_ID_1_${ENV}="$(eval echo \$PANGEA_AUDIT_CONFIG_ID_1_${ENV}_${CLOUD})"
    - export PANGEA_AUDIT_CONFIG_ID_2_${ENV}="$(eval echo \$PANGEA_AUDIT_CONFIG_ID_2_${ENV}_${CLOUD})"
    - export PANGEA_AUDIT_CONFIG_ID_3_${ENV}="$(eval echo \$PANGEA_AUDIT_CONFIG_ID_3_${ENV}_${CLOUD})"
    - export PANGEA_REDACT_CONFIG_ID_1_${ENV}="$(eval echo \$PANGEA_REDACT_CONFIG_ID_1_${ENV}_${CLOUD})"
    - export PANGEA_REDACT_CONFIG_ID_2_${ENV}="$(eval echo \$PANGEA_REDACT_CONFIG_ID_2_${ENV}_${CLOUD})"

    - cd packages/pangea-sdk/

  parallel:
    matrix:
      - ENV: ${SERVICE_AI_GUARD_ENV}
        TEST: ITAIGuardTest
      - ENV: ${SERVICE_AUDIT_ENV}
        TEST: ITAuditTest
      - ENV: ${SERVICE_AUTHN_ENV}
        TEST: ITAuthNTest
      - ENV: ${SERVICE_AUTHZ_ENV}
        TEST: ITAuthZTest
      - ENV: ${SERVICE_EMBARGO_ENV}
        TEST: ITEmbargoTest
      - ENV: ${SERVICE_DOMAIN_INTEL_ENV}
        TEST: ITDomainIntelTest
      - ENV: ${SERVICE_IP_INTEL_ENV}
        TEST: ITIPIntelTest
      - ENV: ${SERVICE_URL_INTEL_ENV}
        TEST: ITURLIntelTest
      - ENV: ${SERVICE_USER_INTEL_ENV}
        TEST: ITUserIntelTest
      - ENV: ${SERVICE_FILE_INTEL_ENV}
        TEST: ITFileIntelTest
      - ENV: ${SERVICE_FILE_SCAN_ENV}
        TEST: ITFileScanTest
      - ENV: ${SERVICE_PROMPT_GUARD_ENV}
        TEST: ITPromptGuardTest
      - ENV: ${SERVICE_REDACT_ENV}
        TEST: ITRedactTest
      - ENV: ${SERVICE_SANITIZE_ENV}
        TEST: ITSanitizeTest
      - ENV: ${SERVICE_SHARE_ENV}
        TEST: ITShareTest
      - ENV: ${SERVICE_VAULT_ENV}
        TEST: ITVaultTest
  script:
    - mvn $MAVEN_CLI_OPTS test -Dtest=${TEST}

building-sdk:
  extends: .sdk-base
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

publishing-sdk:
  extends: .sdk-base
  stage: publish
  script:
    - bash ../../dev/validate_tag.sh $CI_COMMIT_TAG
    - mvn $MAVEN_CLI_OPTS deploy -Dmaven.test.skip=true
  rules:
    - if: $CI_COMMIT_TAG
